export const explanation = {
  heading: 'How this is calculated',
  body: `This calculator compares India's two personal income-tax regimes for a salaried taxpayer and shows which one currently results in lower tax. It models FY 2025-26 (AY 2026-27) — the numbers from Union Budget 2025 — because that is the last financial year whose rules this calculator's rule set has been confirmed against. See the note at the end of this section before relying on it for FY 2026-27 filing.

For each regime, the same five steps run: add salary and other income to get Gross Total Income; subtract that regime's deductions to get Taxable Income; apply that regime's slab rates bracket-by-bracket to get tax before rebate; apply the Section 87A rebate (Old Regime: taxable income up to ₹5,00,000; New Regime: up to ₹12,00,000) including marginal relief just above that line, so a few extra rupees of income can never leave you worse off than someone who earned exactly the threshold; apply surcharge for taxable income above ₹50 lakh (also with marginal relief at each surcharge band, and capped at 25% under the New Regime even past ₹5 crore, versus up to 37% under the Old Regime); then add 4% Health & Education Cess on top of tax plus surcharge.

Old Regime deductions modelled: a ₹50,000 standard deduction, Section 80C (capped at ₹1,50,000), Section 80D health insurance premium (capped at ₹25,000, or ₹50,000 if you're 60 or older), the HRA exemption, and a general "other deductions" field for things like home loan interest under Section 24(b) or the extra NPS deduction under Section 80CCD(1B). New Regime deductions: just a ₹75,000 standard deduction — nearly everything else is disallowed under Section 115BAC.

HRA exemption uses the standard rule — the lowest of: HRA actually received; rent paid minus 10% of Basic+DA; or 50% of Basic+DA in a metro city (Delhi, Mumbai, Kolkata, Chennai) / 40% elsewhere. This calculator only collects one salary figure (matching every other calculator in this project), so Basic+DA is assumed to be 50% of gross salary — a common approximation, and one clearly named and adjustable in this calculator's config.js if your actual Basic+DA differs.

Two things are computed but can't be shown in this project's shared result display, which formats every value as an INR amount: your effective tax rate (tax ÷ gross income, a percentage) and which regime is recommended (a label, not a number). Both are still returned by this calculator's underlying function — you can see the recommendation by comparing the Old Regime and New Regime total tax figures directly: whichever is lower is the better choice for the numbers you entered.

A note on currency: since this calculator only has one age field, Section 80D's enhanced ₹50,000 cap for premium paid specifically on senior-citizen parents isn't separately modelled — only your own age is used. Tax rules change with every Union Budget, typically presented around 1 February. This calculator was built on 8 August 2026, during FY 2026-27, but the FY 2026-27 Budget's contents were not available when its rules were written, so it deliberately uses the last confirmed year (FY 2025-26) instead of guessing at what may have changed. Check the Income Tax Department's official site (incometax.gov.in) for the financial year you're actually filing for.`,
  disclaimer:
    'This is an estimation tool for planning purposes only, not tax advice. Verify your actual tax liability using official Income Tax Department resources or a qualified tax professional before making any filing or investment decision.',
}