export const config = {
  id: 'retirement',
  title: 'Retirement Planning Calculator',
  shortDescription: 'Estimate how much you may need for retirement and whether your current savings plan is on track.',
  category: 'Retirement Planning',
  fields: [
    { name: 'currentAge', label: 'How old are you now?', unit: 'years', defaultValue: 30, min: 18, max: 70, step: 1 },
    { name: 'retirementAge', label: 'At what age do you want to retire?', unit: 'years', defaultValue: 60, min: 35, max: 75, step: 1 },
    { name: 'lifeExpectancy', label: 'How long do you want the plan to cover you?', unit: 'years', defaultValue: 85, min: 50, max: 100, step: 1 },
    { name: 'currentMonthlyExpenses', label: 'How much do you spend each month today?', unit: '₹', defaultValue: 50000, min: 0, max: 1000000, step: 1000 },
    { name: 'existingCorpus', label: 'How much have you already saved for retirement?', unit: '₹', defaultValue: 500000, min: 0, max: 100000000, step: 10000 },
    { name: 'preRetirementReturn', label: 'Expected yearly return before retirement', unit: '%', defaultValue: 12, min: 0, max: 30, step: 0.5 },
    { name: 'postRetirementReturn', label: 'Expected yearly return after retirement', unit: '%', defaultValue: 7, min: 0, max: 30, step: 0.5 },
    { name: 'inflation', label: 'Expected yearly increase in living costs', unit: '%', defaultValue: 6, min: 0, max: 25, step: 0.5 },
    { name: 'newInvestmentReturn', label: 'Expected yearly return on new monthly investments', unit: '%', defaultValue: 12, min: 0, max: 30, step: 0.5 },
  ],
  resultFields: [
    { name: 'requiredRetirementCorpus', label: 'Estimated money needed at retirement', primary: true },
    { name: 'monthlyExpensesToday', label: 'Monthly spending today' },
    { name: 'monthlyExpensesAtRetirement', label: 'Estimated monthly spending at retirement' },
    { name: 'projectedExistingCorpus', label: 'What your current retirement savings could become' },
    { name: 'additionalCorpusRequired', label: 'Extra retirement savings you may need' },
    { name: 'corpusSurplus', label: 'Estimated savings above the target' },
    { name: 'requiredMonthlyInvestment', label: 'Estimated monthly investment needed' },
    { name: 'sustainableMonthlyIncome', label: 'Estimated monthly income from your current savings path' },
  ],
}
