export const config = {
  id: 'goal-based',
  title: 'Goal Planning Calculator',
  shortDescription: 'Find out how much you may need to invest regularly to reach a money goal.',
  category: 'Planning',
  fields: [
    { name: 'targetAmount', label: 'How much money do you want to have for your goal?', unit: '₹', defaultValue: 1000000, min: 0, max: 100000000, step: 10000 },
    { name: 'currentSavings', label: 'How much have you already saved for this goal?', unit: '₹', defaultValue: 0, min: 0, max: 100000000, step: 10000 },
    { name: 'years', label: 'How many years until you need the money?', unit: 'years', defaultValue: 10, min: 1, max: 40, step: 1 },
    { name: 'annualReturnRate', label: 'Expected yearly return on your savings/investments', unit: '%', defaultValue: 12, min: 0, max: 30, step: 0.5 },
    { name: 'investmentFrequency', label: 'How often will you add money? (0 = Monthly, 1 = Yearly)', unit: '', defaultValue: 0, min: 0, max: 1, step: 1 },
    { name: 'expectedInflation', label: 'Expected yearly increase in the goal cost', unit: '%', defaultValue: 0, min: 0, max: 15, step: 0.1 },
  ],
  resultFields: [
    { name: 'requiredInvestment', label: 'Investment needed to reach the goal', primary: true },
    { name: 'requiredMonthlyInvestment', label: 'Estimated monthly amount to invest' },
    { name: 'requiredAnnualInvestment', label: 'Estimated yearly amount to invest' },
    { name: 'targetAmountAtGoal', label: 'Estimated goal amount when you need it' },
    { name: 'futureValueOfExistingSavings', label: 'What your current savings could become' },
    { name: 'requiredAdditionalCorpus', label: 'Extra amount still needed' },
    { name: 'totalContributions', label: 'Total new money you add' },
    { name: 'totalReturns', label: 'Estimated growth' },
    { name: 'projectedFinalValue', label: 'Projected value at the goal date' },
    { name: 'surplusOrShortfall', label: 'Estimated surplus or shortfall' },
  ],
}
