const SEO = {
  sip: { title: 'SIP Calculator – Estimate SIP Returns | FinCalc', description: 'Estimate SIP maturity, total investment and potential returns from your monthly contribution, expected return and time period.' },
  lumpsum: { title: 'Lump Sum Calculator – Estimate Investment Growth | FinCalc', description: 'Estimate how a one-time investment could grow using the amount invested, expected return and investment period.' },
  cagr: { title: 'CAGR Calculator – Calculate Annualized Growth | FinCalc', description: 'Calculate CAGR from starting value, ending value and investment period to understand annualized investment growth.' },
  swp: { title: 'SWP Calculator – Estimate Withdrawals & Balance | FinCalc', description: 'Estimate systematic withdrawals, total withdrawals and remaining investment under your return and withdrawal assumptions.' },
  'goal-based': { title: 'Goal-Based Investment Calculator | FinCalc', description: 'Estimate how much you may need to invest to reach a target amount by a chosen date using return and goal assumptions.' },
  fd: { title: 'FD Calculator – Estimate Maturity & Interest | FinCalc', description: 'Estimate fixed deposit maturity and interest using deposit amount, rate and tenure.' },
  rd: { title: 'RD Calculator – Estimate Maturity & Interest | FinCalc', description: 'Estimate recurring deposit maturity and interest from monthly deposit, interest rate and tenure.' },
  ppf: { title: 'PPF Calculator – Estimate Maturity & Returns | FinCalc', description: 'Estimate PPF maturity and interest using yearly contribution, rate and investment period.' },
  EPF: { title: 'EPF Calculator – Estimate Corpus & Savings | FinCalc', description: 'Estimate EPF corpus growth from salary, contribution, interest rate and years to retirement.' },
  EMI: { title: 'EMI Calculator – Calculate EMI & Total Interest | FinCalc', description: 'Calculate monthly loan EMI, total interest and total repayment from loan amount, rate and tenure.' },
  'home-loan': { title: 'Home Loan EMI Calculator – Estimate Payments | FinCalc', description: 'Estimate home loan EMI, total interest and repayment using loan amount, rate and tenure.' },
  'loan-eligibility': { title: 'Loan Eligibility Calculator – Estimate Borrowing Capacity | FinCalc', description: 'Estimate potential loan eligibility from income, existing obligations, rate and repayment assumptions.' },
  'personal-loan': { title: 'Personal Loan EMI Calculator – Estimate Monthly Payment | FinCalc', description: 'Estimate personal loan EMI, total interest and repayment from loan amount, rate and repayment period.' },
  'car-loan': { title: 'Car Loan EMI Calculator – Estimate Loan Payments | FinCalc', description: 'Estimate monthly car loan EMI, total interest and repayment using loan amount, rate and tenure.' },
  'home-loan-affordability': { title: 'Home Loan Affordability Calculator | FinCalc', description: 'Estimate a practical home loan amount from income, existing payments, rate and repayment capacity.' },
  'down-payment': { title: 'Down Payment Calculator – Estimate Upfront Cost | FinCalc', description: 'Calculate an estimated down payment and remaining amount to finance for a major purchase.' },
  'loan-comparison': { title: 'Loan Comparison Calculator – Compare Total Cost | FinCalc', description: 'Compare two loan options using EMI, interest, tenure and total repayment to see which costs more.' },
  'loan-prepayment': { title: 'Loan Prepayment Calculator – Estimate Interest Savings | FinCalc', description: 'Estimate how a loan prepayment could change your balance, tenure and total interest.' },
  'debt-payoff': { title: 'Debt Payoff Calculator – Estimate Debt-Free Time | FinCalc', description: 'Estimate how long it may take to repay debt and how much interest you could pay under repayment assumptions.' },
  'debt-snowball': { title: 'Debt Snowball Calculator – Plan Debt Payoff Order | FinCalc', description: 'Plan a debt snowball strategy by ordering debts and estimating repayment progress.' },
  'debt-avalanche': { title: 'Debt Avalanche Calculator – Plan Interest-First Payoff | FinCalc', description: 'Estimate an interest-first debt repayment plan that prioritizes higher-rate balances.' },
  'credit-card-interest': { title: 'Credit Card Interest Calculator – Estimate Charges | FinCalc', description: 'Estimate credit-card interest and repayment cost from balance, rate and payment assumptions.' },
  'credit-card-emi': { title: 'Credit Card EMI Calculator – Estimate EMI & Interest | FinCalc', description: 'Estimate monthly EMI, total interest and repayment for a credit-card purchase converted to EMI.' },
  'loan-balance-transfer': { title: 'Loan Balance Transfer Calculator – Compare Loan Cost | FinCalc', description: 'Compare a current loan with a balance-transfer option using rate, tenure, fees and interest savings.' },
  'salary-take-home': { title: 'Take-Home Salary Calculator – Estimate In-Hand Pay | FinCalc', description: 'Estimate monthly take-home pay after common salary deductions using income and applicable assumptions.' },
  'ctc-to-in-hand': { title: 'CTC to In-Hand Salary Calculator | FinCalc', description: 'Estimate monthly in-hand salary from CTC and salary components to compare job offers more clearly.' },
  'salary-hike': { title: 'Salary Hike Calculator – Calculate New Salary | FinCalc', description: 'Calculate revised salary and increase amount from your current salary and hike percentage.' },
  'salary-increment': { title: 'Salary Increment Calculator – Calculate Revised Pay | FinCalc', description: 'Calculate salary increase, revised pay and percentage change between old and new salary.' },
  'job-offer-comparison': { title: 'Job Offer Comparison Calculator | FinCalc', description: 'Compare job offers using salary, take-home pay and compensation assumptions to support a clearer decision.' },
  gratuity: { title: 'Gratuity Calculator – Estimate Gratuity Amount | FinCalc', description: 'Estimate gratuity based on salary and years of service using the assumptions provided by the calculator.' },
  'notice-period-salary': { title: 'Notice Period Salary Calculator | FinCalc', description: 'Estimate salary received during a notice period using monthly pay, days and applicable assumptions.' },
  bonus: { title: 'Bonus Calculator – Estimate Bonus & Total Pay | FinCalc', description: 'Estimate bonus amount and resulting total compensation from salary and bonus assumptions.' },
  'overtime-pay': { title: 'Overtime Pay Calculator – Estimate Extra Pay | FinCalc', description: 'Estimate overtime earnings from hourly pay, overtime hours and the applicable overtime rate.' },
  'leave-encashment': { title: 'Leave Encashment Calculator – Estimate Unused Leave Pay | FinCalc', description: 'Estimate the value of unused leave using salary and eligible leave assumptions.' },
  nps: { title: 'NPS Calculator – Estimate Corpus & Retirement Income | FinCalc', description: 'Estimate NPS corpus and retirement income from contributions, return assumptions and years to retirement.' },
  'nps-vs-epf': { title: 'NPS vs EPF Calculator – Compare Retirement Growth | FinCalc', description: 'Compare estimated NPS and EPF outcomes using contributions, return assumptions and retirement timelines.' },
  fire: { title: 'FIRE Calculator – Estimate Financial Independence | FinCalc', description: 'Estimate the savings and investment path toward financial independence using spending, savings and return assumptions.' },
  retirement: { title: 'Retirement Calculator – Estimate Corpus & Savings | FinCalc', description: 'Estimate the retirement corpus you may need and the savings required using spending, horizon and return assumptions.' },
  'retirement-withdrawal': { title: 'Retirement Withdrawal Calculator – Estimate Withdrawals | FinCalc', description: 'Estimate retirement withdrawals and how your investment balance may change under return and withdrawal assumptions.' },
  'retirement-income': { title: 'Retirement Income Calculator – Estimate Retirement Income | FinCalc', description: 'Estimate potential retirement income from your corpus using withdrawal, return and time-horizon assumptions.' },
  'retirement-age': { title: 'Retirement Age Calculator – Estimate Retirement Timing | FinCalc', description: 'Estimate a possible retirement age from savings, spending, investment returns and retirement goals.' },
  'fi-progress': { title: 'Financial Independence Progress Calculator | FinCalc', description: 'Estimate how close you may be to financial independence using assets, savings, spending and return assumptions.' },
  'future-net-worth': { title: 'Future Net Worth Calculator – Estimate Wealth | FinCalc', description: 'Estimate how savings, assets, liabilities and investment growth could change your net worth over time.' },
  'wealth-accumulation': { title: 'Wealth Accumulation Calculator – Estimate Growth | FinCalc', description: 'Estimate how regular savings and investment growth could build wealth over a chosen time period.' },
  'monthly-investment-required': { title: 'Monthly Investment Required Calculator | FinCalc', description: 'Calculate an estimated monthly investment needed to reach a target amount by a chosen date.' },
  'retirement-gap': { title: 'Retirement Gap Calculator – Estimate Savings Gap | FinCalc', description: 'Estimate the gap between projected retirement resources and the amount you may need for your planned retirement.' },
  'mutual-fund-return': { title: 'Mutual Fund Return Calculator – Estimate Returns | FinCalc', description: 'Estimate mutual fund investment growth and returns from amount invested, return assumption and time period.' },
  'mutual-fund-sip-return': { title: 'Mutual Fund SIP Return Calculator – Estimate Growth | FinCalc', description: 'Estimate mutual fund SIP maturity, total contributions and potential returns from monthly investing.' },
  'portfolio-return': { title: 'Portfolio Return Calculator – Estimate Overall Return | FinCalc', description: 'Estimate portfolio return from multiple investments using values, allocations and return assumptions.' },
  'stock-profit-loss': { title: 'Stock Profit & Loss Calculator – Calculate Gain or Loss | FinCalc', description: 'Calculate stock profit or loss from buy price, sell price and quantity.' },
  'stock-average-price': { title: 'Stock Average Price Calculator – Calculate New Average | FinCalc', description: 'Calculate weighted average stock purchase price after adding another purchase at a different price.' },
  'dividend-income': { title: 'Dividend Income Calculator – Estimate Dividend Earnings | FinCalc', description: 'Estimate dividend income from shares owned, dividend per share and payment assumptions.' },
  'dividend-yield': { title: 'Dividend Yield Calculator – Calculate Dividend Yield | FinCalc', description: 'Calculate dividend yield from stock price and dividend per share to understand income relative to price.' },
  'capital-gains': { title: 'Capital Gains Calculator – Estimate Investment Gains | FinCalc', description: 'Estimate capital gain or loss from purchase price, sale price and investment-related costs.' },
  'stock-cagr': { title: 'Stock CAGR Calculator – Calculate Annualized Growth | FinCalc', description: 'Calculate stock compound annual growth rate from starting value, ending value and holding period.' },
  'gold-investment-return': { title: 'Gold Investment Return Calculator – Estimate Growth | FinCalc', description: 'Estimate return on a gold investment from purchase value, current value and holding period.' },
  'net-worth': { title: 'Net Worth Calculator – Calculate Assets Minus Debt | FinCalc', description: 'Calculate net worth by adding assets and subtracting debts and other liabilities from the total.' },
  'income-tax': { title: 'Income Tax Calculator – Estimate Tax & Take-Home Income | FinCalc', description: 'Estimate income tax and post-tax income using the assumptions available in the calculator.' },
  inflation: { title: 'Inflation Calculator – Calculate Future Money Value | FinCalc', description: 'See how inflation can change purchasing power over time using amount, inflation rate and years.' },
  education: { title: 'Education Cost Calculator – Estimate Future Cost | FinCalc', description: 'Estimate future education costs using current costs, inflation and the years until the goal.' },
  'rent-vs-buy': { title: 'Rent vs Buy Calculator – Compare Housing Costs | FinCalc', description: 'Compare estimated long-term renting and buying costs using housing, financing and investment assumptions.' },
  'car-loan-vs-cash': { title: 'Car Loan vs Cash Calculator – Compare Financing | FinCalc', description: 'Compare the estimated cost of financing a car with paying cash and investing the money instead.' },
  'education-loan': { title: 'Education Loan Calculator – Estimate EMI & Cost | FinCalc', description: 'Estimate education loan EMI, total interest and repayment using loan amount, rate and tenure.' },
  'wedding-goal': { title: 'Wedding Goal Calculator – Plan Monthly Savings | FinCalc', description: 'Estimate how much you may need to save or invest each month to reach a future wedding budget.' },
  'child-education-planning': { title: 'Child Education Planning Calculator | FinCalc', description: 'Estimate future education costs and the savings or investment needed for your child’s education goal.' },
  'health-insurance-requirement': { title: 'Health Insurance Requirement Calculator | FinCalc', description: 'Estimate a starting point for health insurance coverage using income, family and expense assumptions.' },
  'life-insurance-requirement': { title: 'Life Insurance Requirement Calculator | FinCalc', description: 'Estimate a starting point for life insurance coverage using income, dependants, liabilities and financial goals.' },
  'financial-independence-date': { title: 'Financial Independence Date Calculator | FinCalc', description: 'Estimate when you may reach financial independence from savings, spending, assets and return assumptions.' },
}

export function getCalculatorSEO(id) {
  return SEO[id] || null
}
